
package com.fitness.wsclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HealthService", targetNamespace = "http://fitness.org/", wsdlLocation = "http://localhost:8080/HealthFitness/HealthService?wsdl")
public class HealthService
    extends Service
{

    private final static URL HEALTHSERVICE_WSDL_LOCATION;
    private final static WebServiceException HEALTHSERVICE_EXCEPTION;
    private final static QName HEALTHSERVICE_QNAME = new QName("http://fitness.org/", "HealthService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/HealthFitness/HealthService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HEALTHSERVICE_WSDL_LOCATION = url;
        HEALTHSERVICE_EXCEPTION = e;
    }

    public HealthService() {
        super(__getWsdlLocation(), HEALTHSERVICE_QNAME);
    }

    public HealthService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HEALTHSERVICE_QNAME, features);
    }

    public HealthService(URL wsdlLocation) {
        super(wsdlLocation, HEALTHSERVICE_QNAME);
    }

    public HealthService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HEALTHSERVICE_QNAME, features);
    }

    public HealthService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HealthService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BodyFatCalculator
     */
    @WebEndpoint(name = "BodyFatCalculatorPort")
    public BodyFatCalculator getBodyFatCalculatorPort() {
        return super.getPort(new QName("http://fitness.org/", "BodyFatCalculatorPort"), BodyFatCalculator.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BodyFatCalculator
     */
    @WebEndpoint(name = "BodyFatCalculatorPort")
    public BodyFatCalculator getBodyFatCalculatorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://fitness.org/", "BodyFatCalculatorPort"), BodyFatCalculator.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HEALTHSERVICE_EXCEPTION!= null) {
            throw HEALTHSERVICE_EXCEPTION;
        }
        return HEALTHSERVICE_WSDL_LOCATION;
    }

}
